spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/rsSystem?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8"
    username: "zentao"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: create
